name: Build docker images
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push taxcalc image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/tslnc04/taxcalc:latest
          file: Containerfile
          target: taxcalc

      - name: Build and push taxcalcd image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/tslnc04/taxcalcd:latest
          file: Containerfile
          target: taxcalcd
